apiVersion: apps/v1
kind: Deployment
metadata:
  name: hypertool-web
  labels:
    app: hypertool-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hypertool-web
  template:
    metadata:
      labels:
        app: hypertool-web
    spec:
      containers:
        - name: hypertool-web
          image: itssamuelrowe/hypertool-web
          ports:
            - containerPort: 3000
    resources:
      requests:
        memory: "128mb"
        cpu: "250m"
      limits:
        memory: "500m"
        cpu: "500m"
      